{% set name = "ptychodus" %}
{% set version = "0.2.1" %}

package:
  name: ptychodus
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/ptychodus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7c4f7aed6fca148e91afc1e5c4cfef145133d220744fdeb82d4cc334be8584c7

build:
  number: 0

outputs:
  # all optional packages
  - name: ptychodus-all

    build:
      noarch: python

    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('ptychodus', exact=True) }}
        - tike

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # with QT
  - name: ptychodus

    build:
      noarch: python

    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('ptychodus-core', exact=True) }}
        - pyqt

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        - ptychodus --version

  # ptychodus without QT (headless) without optional packages
  - name: ptychodus-core

    script: build-core.sh

    build:
      noarch: python
      entry_points:
        - ptychodus = ptychodus.__main__:main

    requirements:
      host:
        - pip
        - python >=3.9
        - setuptools >=46.4.0
        - setuptools_scm >=6.2
        - setuptools_scm_git_archive
        - wheel
      run:
        - h5py =3.*
        - hdf5-external-filter-plugins-lz4
        - matplotlib-base =3.*
        - numpy =1.*
        - python >=3.9
        - scipy =1.*
        - tifffile =2022.*
        - watchdog =2.*
      run_constrained:
        - pyqt =5.*
        - tike =0.22.*

    test:
      imports:
        - ptychodus
      requires:
        - pip
      commands:
        - pip check
        # - ptychodus --version

about:
  home: https://github.com/AdvancedPhotonSource/ptychodus
  summary: 'Ptychodus is a ptychography analysis front-end.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/AdvancedPhotonSource/ptychodus

extra:
  recipe-maintainers:
    - AdvancedPhotonSource/ptychodus
    - carterbox
    - stevehenke
